### PR TITLE
Delete MatrixMultiplication Interceptor

### PR DESCRIPTION
**Pull request by gamepro65**
Regression caught in Cash, looks like Matrix is now provided so now we are unintentionally were messing with these operations 😅

### CODE REVIEW

**Review by jrodbx — APPROVED** [review]
Yay!  Any tests to delete?

**Comment by gamepro65** [comment]
> Yay! Any tests to delete?

I didn't see any, looked at when we added these interceptors but no tests in that PR

**Comment by TWiStErRob** [comment]
@gamepro65 how did this manifest?

**Comment by gamepro65** [comment]
> @gamepro65 how did this manifest?

We've got a few tests in Cash which use `multiplyMV` and `multiplyMM`. Running those tests resulted in these operations applying twice. Could make a unit test to catch regressions if you were looking for a more concrete example.

**Comment by TWiStErRob** [comment]
Nice. Up to you on the regression, I guess this was triggered by a layoutlib bump? If so, do we see a chance of changing again?

**Pull request merged**
