### PR TITLE
Variant aware

### PR DESCRIPTION
**Pull request by menny**

### CODE REVIEW

**Comment by jrodbx** [comment]
There are a lot of changes which look related to https://github.com/cashapp/paparazzi/pull/135

Can we prune that out?

**Comment by menny** [comment]
This is a draft PR. Waiting for #135 to be merged.

**Comment by jrodbx** [comment]
I see, it's rebased on #135 yet targeted to master.  FYI, you can target the branch in #135, and then when that merges in, Github would retarget this PR to the updated master.  Handy for stacked PRs and parallelizing reviews!

**Review by jrodbx — APPROVED** [review]

**Comment by menny** [comment]
nice, didn't know that.

**Comment by jrodbx** [comment]
Yea so if you have:

master> git checkout branch1
branch1> (commit stuff)
branch1> (push and make PR)
branch1> git checkout branch2
branch2> (commit stuff)
branch2> (push)

Then in Github, when you create the PR you can edit the target branch of branch2 to be branch 1, which affects the diff.  It does mean keeping branch2 up to date every time branch1 updates though, which can be slightly annoying...

**Pull request merged**
