### PR TITLE
Update Gradle Wrapper Validation Action

### PR DESCRIPTION
**Pull request by jrodbx**
https://github.com/gradle/wrapper-validation-action/releases/tag/v1.0.4
In particular, Retry connections to the server on failure (#39)

### CODE REVIEW

**Comment by jrodbx** [comment]
🤣 

Screen Shot 2021-11-15 at 11 09 18 PM

**Comment by JakeWharton** [comment]
https://github.com/cashapp/turbine/blob/trunk/.github/dependabot.yaml

**Review by JakeWharton — APPROVED** [review]
I'm pretty sure v1 implies the latest full version so this change is effectively a no-op

**Comment by jrodbx** [comment]
> I'm pretty sure v1 implies the latest full version so this change is effectively a no-op

Oh so then the retries feature is still broken?

**Pull request merged**
