### PR TITLE
Use managed properties to clean up PrepareResourcesTask

### PR DESCRIPTION
**Pull request by jrodbx**
https://docs.gradle.org/current/userguide/custom_gradle_types.html#managed_properties

### CODE REVIEW

**Review by luis-cortes — APPROVED** [review]

**Review by Egorand — COMMENTED** [review]
Awesome, looks like this should help with configuration caching support 👍

**Comment by jrodbx** [comment]
> Awesome, looks like this should help with configuration caching support 👍 

Managed properties have no impact on configuration caching support.  Besides, the plugin has full support as of https://github.com/cashapp/paparazzi/pull/261.

**Comment by Egorand** [comment]
Ah, okay, just noticed that this change removes references to `project` which config caching prohibits.

**Comment by jrodbx** [comment]
Ah, I see.  Actually, configuration caching prohibits references to project in task actions (annotated by @TaskAction) but not all references to project.  In fact, it would be difficult to remove _all_ references since Project to Gradle is like Context to Android 😂

**Comment by Egorand** [comment]
Haha, fair enough. But glad to hear the project supports config caching!

**Pull request merged**
