### PR TITLE
Migrate Paparazzi to layoutlib 2021.1.1

### PR DESCRIPTION
**Pull request by jrodbx**
Closes https://github.com/cashapp/paparazzi/issues/264

TODO: figure out how to fix PaparazziTest.animationEvents again.... (any ideas?)

2021.1.1 Log:
https://android.googlesource.com/platform/frameworks/layoutlib/+log/dfeaa107ec1f08a240b3af151391cad98292622e

Suspected relevant commits:
- https://android.googlesource.com/platform/frameworks/layoutlib/+/8ef4e9f7c0f8dd02516383ca34d17373551cefb9
- https://android.googlesource.com/platform/frameworks/layoutlib/+/44d1f3dc5de431fdce9296c5ef1c8e02e0b9742b

### CODE REVIEW

**Comment by chrisbanes** [comment]
I've been trying this out this week and hitting the following:

<details>
  <summary>UnsatisfiedLinkError stack trace</summary>

  ```
  java.lang.UnsatisfiedLinkError: 'java.lang.String android.os.SystemProperties.native_get(java.lang.String, java.lang.String)'
	  at android.os.SystemProperties.native_get(Native Method)
	  at android.os.SystemProperties.get(SystemProperties.java:165)
	  at android.os.Build.getString(Build.java:1434)
	  at android.os.Build.<clinit>(Build.java:54)
	  at android.os.Build$VERSION.<clinit>(Build.java:274)
	  at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	  at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042)
	  at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	  at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:186)
	  at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1105)
	  at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1086)
	  at java.base/java.lang.reflect.Field.setInt(Field.java:960)
	  at app.cash.paparazzi.Paparazzi.forcePlatformSdkVersion(Paparazzi.kt:394)
	  at app.cash.paparazzi.Paparazzi.prepare(Paparazzi.kt:137)
	  at app.cash.paparazzi.Paparazzi$apply$statement$1.evaluate(Paparazzi.kt:119)
	  at app.cash.paparazzi.agent.AgentTestRule$apply$1.evaluate(AgentTestRule.kt:17)
  ```
</details>

I've commented it out for now. Any ideas?

**Review by JakeWharton — APPROVED** [review]

**Comment by alashow** [comment]
On M1 Mac, I'm getting this error while trying to run paparazzi:

```
SEVERE: broken: Native layoutlib failed to load
java.lang.UnsatisfiedLinkError: 
Can't load library: /Users/alashov/.gradle/caches/transforms-3/ea0b7f66c989590baafb23b3b92901e4/transformed/layoutlib-native-macarm-2021.1.1-573f070/data/mac/lib64/libandroid_runtime.dylib
``` 

I checked  and `/Users/alashov/.gradle/caches/transforms-3/ea0b7f66c989590baafb23b3b92901e4/transformed/layoutlib-native-macarm-2021.1.1-573f070/data/mac/lib64/libandroid_runtime.dylib` file doesn't exist. But there is `mac-arm` folder instead: `/Users/alashov/.gradle/caches/transforms-3/ea0b7f66c989590baafb23b3b92901e4/transformed/layoutlib-native-macarm-2021.1.1-573f070/data/mac-arm/lib64/libandroid_runtime.dylib`

So I tried renaming `mac-arm` folder to `mac` just to see what happens, then it failed with this message:
```
SEVERE: broken: Native layoutlib failed to load
java.lang.UnsatisfiedLinkError: /Users/alashov/.gradle/caches/transforms-3/ea0b7f66c989590baafb23b3b92901e4/transformed/layoutlib-native-macarm-2021.1.1-573f070/data/mac/lib64/libandroid_runtime.dylib: dlopen(/Users/alashov/.gradle/caches/transforms-3/ea0b7f66c989590baafb23b3b92901e4/transformed/layoutlib-native-macarm-2021.1.1-573f070/data/mac/lib64/libandroid_runtime.dylib, 0x0001): 
tried: '/Users/alashov/.gradle/caches/transforms-3/ea0b7f66c989590baafb23b3b92901e4/transformed/layoutlib-native-macarm-2021.1.1-573f070/data/mac/lib64/libandroid_runtime.dylib'
 (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/lib/libandroid_runtime.dylib' (no such file)`

**Comment by saket** [comment]
@alashow can you share the output of `System.getProperty("os.arch")` on your machine?

**Comment by alashow** [comment]
It prints `x86_64`. While `/usr/bin/arch` prints `arm64`

**Comment by chrisbanes** [comment]
Sounds like you're using an x86 JVM through Rosetta. Try installing an ARM JVM (Zulu, Azul, etc).

**Pull request merged**
