### PR TITLE
Fix AndroidX font-family loading with ASM transform on ResourcesCompat

### LINKED ISSUE #488: Tests fails when using AndroidX font-family
**Description**
It seems like `ResourcesInterceptor` overrides to use the platform Resources.getFont instead of the AndroidX `ResourcesCompat`. This causes a problem when using a font-family that only specifies `app:` attributes, instead of `android:` attributes.

**Steps to Reproduce**
Use an AppTheme that sets `textAppearance` with a font-family like:
```xml
<?xml version="1.0" encoding="utf-8"?>
<font-family xmlns:app="http://schemas.android.com/apk/res-auto">
    <font
        app:font="@font/fk_grotesk_neue_regular"
        app:fontStyle="normal"
        app:fontWeight="400" />

    <font
        app:font="@font/fk_grotesk_neue_medium"
        app:fontStyle="normal"
        app:fontWeight="500" />

    <font
        app:font="@font/fk_grotesk_neue_bold"
        app:fontStyle="normal"
        app:fontWeight="700" />

</font-family>
```

By adding `android:` prefix the tests can inflate everything again.
```xml
<font-family xmlns:app="http://schemas.android.com/apk/res-auto"
xmlns:android="http://schemas.android.com/apk/res/android">
<font
    android:font="@font/fk_grotesk_neue_regular"
    android:fontStyle="normal"
    android:fontWeight="400"
    app:font="@font/fk_grotesk_neue_regular"
    app:fontStyle="normal"
    app:fontWeight="400" />

<font
    android:font="@font/fk_grotesk_neue_medium"
    android:fontStyle="normal"
    android:fontWeight="500"
    app:font="@font/fk_grotesk_neue_medium"
    app:fontStyle="normal"
    app:fontWeight="500" />

<font
    android:font="@font/fk_grotesk_neue_bold"
    android:fontStyle="normal"
    android:fontWeight="700"
    app:font="@font/fk_grotesk_neue_bold"
    app:fontStyle="normal"
    app:fontWeight="700" />

</font-family>
```

**Expected behavior**
It seems like the behaviour was added because of this bug https://issuetracker.google.com/issues/156065472 which now is supposed to be fixed. Could the Interception be removed?

**Additional information:**
- Paparazzi Version: 1.0.0
- OS: MacOS 12.3.1 
- Compile SDK: 32
- Gradle Version: 7.4.1
- Android Gradle Plugin Version: 7.2.1

**Screenshots**
-

### PR DESCRIPTION
**Pull request by tevjef**
Adapt bytecode transformation done in [Android Studio](https://cs.android.com/android-studio/platform/tools/adt/idea/+/mirror-goog-studio-main:android/src/com/android/tools/idea/rendering/classloading/ResourcesCompatTransform.kt) to be performed during unit test compilation.

Resolves #488.

### CODE REVIEW

**Comment by tevjef** [comment]
@jrodbx I think I need some help figuring out why windows tests are failing.

**Comment by TWiStErRob** [comment]
@jrodbx any reason for not publishing test reports to GHA artifacts?

**Comment by TWiStErRob** [comment]
@tevjef I ran the tests on Windows 10 / Java 11 locally:
Failing test: `PaparazziPluginTest.customFontsInCode`, it's expecting a successful build in the test, but gets `android.content.res.Resources$NotFoundException at CustomFontsTest.kt:45`

Command to repro:
```shell
gradlew -p paparazzi :paparazzi-gradle-plugin:test --tests app.cash.paparazzi.gradle.PaparazziPluginTest.customFontsInCode
```

Attached the two output reports:
[paparazzi-gradle-plugin-report.zip](https://github.com/cashapp/paparazzi/files/10391502/paparazzi-gradle-plugin-report.zip)

[custom-fonts-code-report.zip](https://github.com/cashapp/paparazzi/files/10391501/custom-fonts-code-report.zip)

Relevant stack:
```
android.content.res.Resources$NotFoundException: Font resource ID #0x7f090001 could not be retrieved.
	at app//androidx.core.content.res.ResourcesCompat.loadFont(ResourcesCompat.java:574)
	at app//androidx.core.content.res.ResourcesCompat.getFont(ResourcesCompat.java:411)
	at app//app.cash.paparazzi.plugin.test.CustomFontsTest.customFontInTextViewInCode(CustomFontsTest.kt:45)
```
Might-be-relevant logs:
```
Jan 11, 2023 10:52:48 AM app.cash.paparazzi.internal.PaparazziLogger logAndroidFramework
INFO: ThemeUtils [4]: View class androidx.appcompat.widget.AppCompatImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
Jan 11, 2023 10:52:48 AM app.cash.paparazzi.internal.PaparazziLogger logAndroidFramework
INFO: ThemeUtils [4]: View class androidx.appcompat.widget.AppCompatTextView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
```

**Comment by TWiStErRob** [comment]
Had a quick look at the code, but didn't debug, I would suspect this to trigger on Windows only:
https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:core/core/src/main/java/androidx/core/content/res/ResourcesCompat.java;l=606-613?q=androidx.core.content.res.ResourcesCompat

**Comment by jrodbx** [comment]
> @jrodbx any reason for not publishing test reports to GHA artifacts?

Mistake.  https://github.com/cashapp/paparazzi/pull/687

**Comment by jrodbx** [comment]
> @jrodbx I think I need some help figuring out why windows tests are failing.

MacOS
```
file: /Users/jrod/Development/paparazzi/paparazzi/paparazzi-gradle-plugin/src/test/projects/custom-fonts-code/build/intermediates/merged_res/debug/font/cashmarket_medium.xml
```

Windows
```
file: D:\a\paparazzi\paparazzi\paparazzi\paparazzi-gradle-plugin\src\test\projects\custom-fonts-code\build\intermediates\merged_res\debug\font\cashmarket_medium.xml
```

**Comment by jrodbx** [comment]
I think reverting the latest changes and instead figuring out if there's a way to pass in the path in a platform-agnostic way, might work better?

Also, does this issue also occur on Windows with Android Studio Electric Eel?  i.e., does the resource transform simply not work?  Might be something to file an issue on Google's issue tracker, if so.

**Comment by tevjef** [comment]
@jrodbx Hey sorry, between PTO and a heavy day workload I haven't had time to think deeper about a fix. Furthermore, debugging has been complicated by my lack of a Windows workspace. 

My latest commits were added on the assumption that the `!file.contains("res/")` in `ResourcesCompat` short-circuit is still triggered on Windows because of the backslashed file path. The additional bytecode transforms to replace `res/` with `res\`  doesn't seem to work.

My next steps are setting up a Windows VM to more accurately determine what's going on.

**Comment by tevjef** [comment]
@jrodbx I was unsuccessful in finding a solution that will also work across platforms. Feel free to close this PR.

**Pull request closed without merging**
